<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
</head>
<body style="background: #3d434e; text-align: center; margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
    <table cellpadding="0" cellspacing="0" width="600" style="margin: 0 auto;">
        <tbody>
            <tr>
                <td align="center" style="padding: 30px 0"><img src="https://apps.stacksight.io/apps/assets/img/email/template/logo.png" alt="Logo"/></td>
            </tr>
            <tr>
                <td align="center" style="background-color: #ee534f; padding: 50px 26px 0px 26px;">
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tbody>
                            <tr>
                                <td style="color: #ffffff; text-align: center">
                                    <span><strong>{{host}}</strong> invited you to checkout</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="color: #ffffff; text-align: center">
                                    <h1 style="font-size: 40px; color: #ffffff">Application Insight</h1>
                                </td>
                            </tr>
                            <tr>
                                <td style="color: #ffffff; text-align: center;">
                                    <span style="font-size: 20px">From {{app}}</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="color: #ffffff; text-align: center; padding-top: 32px">
                                    <img src="https://apps.stacksight.io/apps/assets/img/email/template/main_banner.png" alt="banner"/>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table cellpadding="0" cellspacing="0" style="background-color: #ffffff; font-size: 14px; padding: 56px 76px;" width="100%">
                        <tbody>
                            <tr>
                                <td style="color: #000000; text-align: center">
                                    <span>Click on the button below to join the account:</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="color: #000000; text-align: center; ">
                                    <a href="{{link}}" style="text-decoration: none; -webkit-box-shadow: inset 0px -6px 0px -3px rgba(0,0,0,0.75); -moz-box-shadow: inset 0px -6px 0px -3px rgba(0,0,0,0.75); box-shadow: inset 0px -6px 0px -3px rgba(0,0,0,0.75); border-radius: 24px; margin: 10px 0 0 100px; background-color: #58b855; padding: 12px 0; display: block; width: 250px; color: #ffffff; font-weight: bold">CONFIRM INVITATION</a>
                                </td>
                            </tr>
                            <tr>
                                <td style="color: #000000; text-align: left; padding-top: 40px">
                                    <p>
                                        Hello {{guest}}, {{host}} invited you to checkout application insights from the group "{{app}}"
                                        <br/><br/><a href="{{link}}" target="_blank">Checkout app insights here</a>
                                        <br/><br/>You are getting these emails because someone invited you to view his app analysis stream from Stacksight.io. sign in <a href="{{link}}">here</a>
                                        <br/><br/>Thanks, The Stacksight team!
                                    </p>
                                    <p>
                                        Feel free to contact us with any questions at <a href="mailto:info@stacksight.com" style="color: #ee534f; text-decoration: underline">info@stacksight.com</a>.
                                    </p>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table cellpadding="0" cellspacing="0" style="font-size: 14px; padding: 20px 0; color: #ffffff" width="100%">
                        <tbody>
                            <tr>
                                <td style="text-align: left">© 2016 www.Stacksight.io Ltd.</td>
                                <td style="text-align: right">
                                    <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_fb.png" alt="Facebook"/></a>
                                    <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_lin.png" alt="LinkedIn"/></a>
                                    <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_tw.png" alt="Tweeter"/></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>