<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
</head>
<body style="background: #3d434e; text-align: center; margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
<table cellpadding="0" cellspacing="0" width="600" style="margin: 0 auto;">
    <tbody>
    <tr>
        <td align="center" style="padding: 30px 0"><img src="https://apps.stacksight.io/apps/assets/img/email/template/logo.png" alt="Logo"/></td>
    </tr>
    <tr>
        <td align="center" style="background-color: #ee534f; padding: 50px 0px 0px 0px;">
            <table cellpadding="0" cellspacing="0" width="100%">
                <tbody>
                <tr>
                    <td style="color: #ffffff; text-align: center">
                        <h1 style="font-size: 40px; color: #ffffff">Critical Update</h1>
                    </td>
                </tr>
                <tr>
                    <td style="color: #ffffff; text-align: center; padding-top: 32px">
                        <img src="https://apps.stacksight.io/apps/assets/img/email/template/critical_update.png" alt="banner"/>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table cellpadding="0" cellspacing="0" style="background-color: #ffffff; font-size: 14px; padding: 56px 76px;" width="100%">
                <tbody>
                <tr>
                    <td style="color: #000000; text-align: center">
                        Hello <strong>{{name}}</strong>
                        <p>You have {{upcount}} critical updates in {{stack_name}} {{stack_url}} stack.</p>
                        <p>({{adjust_date}}).</p>
                        <br/>
                        <p>For more details go here</p>
                        <p><a href="{{link}}">{{link}}</a></p>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table cellpadding="0" cellspacing="0" style="font-size: 14px; padding: 20px 0; color: #ffffff" width="100%">
                <tbody>
                <tr>
                    <td style="text-align: left">© 2016 www.Stacksight.io Ltd.</td>
                    <td style="text-align: right">
                        <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_fb.png" alt="Facebook"/></a>
                        <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_lin.png" alt="LinkedIn"/></a>
                        <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_tw.png" alt="Tweeter"/></a>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>