<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
</head>
<body style="background: #3d434e; text-align: center; margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
<table cellpadding="0" cellspacing="0" width="600" style="margin: 0 auto;">
    <tbody>
    <tr>
        <td align="center" style="padding: 30px 0"><img src="https://apps.stacksight.io/apps/assets/img/email/template/logo.png" alt="Logo"/></td>
    </tr>
    <tr>
        <td align="center" style="background-color: #ee534f; padding: 50px 0px 0px 0px;">
            <table cellpadding="0" cellspacing="0" width="100%">
                <tbody>
                <tr>
                    <td style="color: #ffffff; text-align: center">
                        <h1 style="font-size: 40px; color: #ffffff">Welcome to stacksight!</h1>
                    </td>
                </tr>
                <tr>
                    <td style="color: #ffffff; text-align: center;">
                        <span style="font-size: 20px">To start getting open-source insights & compliance recommendations perform the next steps.</span>
                    </td>
                </tr>
                <tr>
                    <td style="color: #ffffff; text-align: center; padding-top: 32px">
                        <img src="https://apps.stacksight.io/apps/assets/img/email/template/welcome_main_banner.png" alt="banner"/>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table cellpadding="0" cellspacing="0" style="background-color: #ffffff; font-size: 14px; padding: 56px 76px;" width="100%">
                <tbody>
                <tr>
                    <td style="color: #000000; text-align: left">
                        <ol style="margin-left: -24px; margin-bottom:24px">
                            <li><a href="http://stacksight.io/docs/" target="_blank">Download and enable stacksight</a></li>
                            <li style="padding-top:10px"><a href="https://apps.stacksight.io/#!/apps" target="_blank">Create your first group</a> and you can share its insights with add it collaborators.</li>
                            <li style="padding-top:10px">Within that group - create a new stack in it will generate an embed code to insert into your configuration file. (you can also retrieve it from an existing sites by going to stack->settings.
                                Insert the embed in to your config (wp-config.php in wordpress, settings.php in drupal).</li>
                        </ol>
                        <p>
                        Congratulations! You are now running stacksight insights.<br/>
                        To learn more about stacksight installation <a href="http://stacksight.io/docs/" target="_blank">go to here</a>.<br/>
                        Thanks again for signing up!<br/>
                        The stacksight team.
                        </p>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table cellpadding="0" cellspacing="0" style="font-size: 14px; padding: 20px 0; color: #ffffff" width="100%">
                <tbody>
                <tr>
                    <td style="text-align: left">© 2016 www.Stacksight.io Ltd.</td>
                    <td style="text-align: right">
                        <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_fb.png" alt="Facebook"/></a>
                        <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_lin.png" alt="LinkedIn"/></a>
                        <a href="#"><img src="https://apps.stacksight.io/apps/assets/img/email/template/ico_tw.png" alt="Tweeter"/></a>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>